apiVersion: v1
entries:
  chartBt:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2026-04-27T14:11:33.794730664Z"
    description: A Helm chart for Kubernetes
    digest: 1cbb2283847581837cc400f5ac7b67aef71b32786fc5065efa23ec14aab16cdf
    name: chartBt
    type: application
    urls:
    - https://VerdeCard-BusinessTech.github.io/helm-bt/charts/chartBt-0.1.0.tgz
    version: 0.1.0
generated: "2026-04-27T14:11:33.794008952Z"
