apiVersion: v1
entries:
  chartBt:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2026-04-27T14:57:24.379099795Z"
    description: A Helm chart for Kubernetes
    digest: 09ce26696fa3b59eb43d4abfda4ad9fbd38668a6a81a5d25797c41eb8ffd832e
    name: chartBt
    type: application
    urls:
    - https://VerdeCard-BusinessTech.github.io/helm-bt/charts/chartBt-0.1.0.tgz
    version: 0.1.0
generated: "2026-04-27T14:57:24.378200975Z"
