apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.projectName }}-service
  namespace: {{ .Release.Namespace }}
  labels:
    k8s-app: {{ .Values.projectName }}
    qcloud-app: {{ .Values.projectName }}
spec:
  ports:
  {{- range .Values.container.ports }}
  - name: {{ .name }}
    port: {{ .containerPort }}
    protocol: TCP
    targetPort: {{ .containerPort }}
  {{- end }}
  selector:
    k8s-app: {{ .Values.projectName }}
    qcloud-app: {{ .Values.projectName }}
  type: ClusterIP
